[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rise = "6kQL7PccHpE7yUrsq5TgxFgQc7K7FVbUJShRUPbWfCdS"

[programs.devnet]
rise = "6kQL7PccHpE7yUrsq5TgxFgQc7K7FVbUJShRUPbWfCdS"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
